import os
import re
from datetime import datetime


class CommunicationAgent:
    """Generates a polished, context-aware message reply."""

    OUTPUT_DIR = "output/communications"

    def run(self, task: str) -> dict:
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)
        reply = self._generate_reply(task)

        slug = re.sub(r"[^a-z0-9]+", "-", task.lower())[:40].strip("-")
        ts = datetime.utcnow().strftime("%H%M%S")
        filename = f"reply_{slug}_{ts}.txt"
        filepath = os.path.join(self.OUTPUT_DIR, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(reply)

        return {
            "status": "success",
            "agent": "Communication Agent",
            "file": filepath,
            "reply": reply,
            "message": "Message reply generated and saved.",
        }

    def _generate_reply(self, task: str) -> str:
        task_lower = task.lower()

        if any(w in task_lower for w in ["urgent", "asap", "immediately", "critical"]):
            tone = "urgent and concise"
            opening = "I'm reaching out urgently regarding"
        elif any(w in task_lower for w in ["thank", "appreciate", "grateful"]):
            tone = "warm and appreciative"
            opening = "Thank you so much for"
        elif any(w in task_lower for w in ["meeting", "schedule", "appointment", "call"]):
            tone = "professional and scheduling-focused"
            opening = "I'd be happy to confirm"
        else:
            tone = "professional and informative"
            opening = "I'm writing to follow up regarding"

        timestamp = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")

        return f"""Subject: Re: {task[:60]}

Dear Recipient,

{opening} the matter you raised: "{task[:120]}".

We have reviewed your request thoroughly and are pleased to provide the following update:

Our team has processed all relevant information and the appropriate actions have been initiated.
You can expect a comprehensive follow-up within the next 24–48 business hours.

If you require immediate assistance or have additional questions, please do not hesitate to reach
out directly. We value your time and are committed to providing prompt, high-quality support.

Thank you for your continued trust in our services.

Warm regards,
Almatti AI Communication Agent
Almatti AI Workforce
{timestamp}

---
[Auto-generated by Almatti AI Workforce — Communication Agent | Tone: {tone}]
"""
