import os
import re
from datetime import datetime
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor


class ContentAgent:
    """Generates markdown notes and a PowerPoint presentation."""

    OUTPUT_DIR = "output/presentations"

    def run(self, task: str) -> dict:
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)
        slug = re.sub(r"[^a-z0-9]+", "-", task.lower())[:40].strip("-")
        ts = datetime.utcnow().strftime("%H%M%S")

        notes = self._generate_notes(task)
        notes_file = os.path.join(self.OUTPUT_DIR, f"notes_{slug}_{ts}.md")
        with open(notes_file, "w", encoding="utf-8") as f:
            f.write(notes)

        ppt_file = os.path.join(self.OUTPUT_DIR, f"presentation_{slug}_{ts}.pptx")
        self._generate_pptx(task, ppt_file)

        return {
            "status": "success",
            "agent": "Content + PPT Agent",
            "notes_file": notes_file,
            "ppt_file": ppt_file,
            "notes_preview": notes[:600],
            "message": f"Notes and PPT saved to {self.OUTPUT_DIR}",
        }

    def _generate_notes(self, task: str) -> str:
        return f"""# AI-Generated Notes — Almatti AI Workforce

**Task:** {task}
**Generated:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC

---

## Overview
This document was generated automatically by the **Almatti AI Content Agent**.

## Key Points
- Task analysis completed using natural language processing
- Content structure optimized for clarity and comprehension
- All outputs saved in organized directories

## Task Breakdown
1. **Objective**: {task[:150]}
2. **Approach**: Multi-agent parallel execution
3. **Agents Used**: Controller, Web Builder, Content+PPT, Communication, File Manager
4. **Output Format**: JSON response with file references

## Action Items
- [ ] Review generated website in `/output/websites`
- [ ] Review PPT in `/output/presentations`
- [ ] Distribute message reply from `/output/communications`
- [ ] Confirm file organization in `/output/files`

## Summary
The Almatti AI Workforce successfully parsed and executed the above task using 5 specialized
AI agents running in parallel via Python ThreadPoolExecutor.

---
*Generated by Almatti AI Workforce — Content + PPT Agent*
"""

    def _generate_pptx(self, task: str, filepath: str):
        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        slides_data = [
            ("🤖 Almatti AI Workforce", "Auto-Generated Presentation", True),
            ("Task Overview", task[:200], False),
            ("Agents Deployed", "Web Builder • Content+PPT • Communication • File Manager", False),
            ("Architecture", "FastAPI Backend + Next.js 15 Frontend\nParallel execution via ThreadPoolExecutor", False),
            ("Results", "✅ Website Generated\n✅ Notes Created\n✅ Message Replied\n✅ Files Organized", False),
            ("Thank You", "Powered by Almatti AI Workforce", True),
        ]

        for title_text, body_text, is_title_slide in slides_data:
            layout = prs.slide_layouts[0] if is_title_slide else prs.slide_layouts[1]
            slide = prs.slides.add_slide(layout)
            bg = slide.background.fill
            bg.solid()
            bg.fore_color.rgb = RGBColor(0x0E, 0x0E, 0x0E)

            slide.shapes.title.text = title_text
            slide.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xBA, 0x9E, 0xFF)
            slide.shapes.title.text_frame.paragraphs[0].runs[0].font.size = Pt(36)
            slide.shapes.title.text_frame.paragraphs[0].runs[0].font.bold = True

            if len(slide.placeholders) > 1:
                body = slide.placeholders[1]
                body.text = body_text
                for para in body.text_frame.paragraphs:
                    for run in para.runs:
                        run.font.color.rgb = RGBColor(0xAD, 0xAA, 0xAA)
                        run.font.size = Pt(20)

        prs.save(filepath)
