import os
import re
from datetime import datetime


class WebAgent:
    """Generates a complete HTML/CSS/JS landing page and saves it."""

    OUTPUT_DIR = "output/websites"

    def run(self, task: str) -> dict:
        slug = re.sub(r"[^a-z0-9]+", "-", task.lower())[:40].strip("-")
        filename = f"site_{slug}_{datetime.utcnow().strftime('%H%M%S')}.html"
        filepath = os.path.join(self.OUTPUT_DIR, filename)

        html = self._generate_html(task)
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        return {
            "status": "success",
            "agent": "Web Builder Agent",
            "file": filepath,
            "preview": html[:500] + "...",
            "message": f"Generated website saved to {filepath}",
        }

    def _generate_html(self, task: str) -> str:
        title = task[:60] if len(task) > 60 else task
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      font-family: 'Inter', system-ui, sans-serif;
      background: #0e0e0e;
      color: #e5e2e1;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    }}
    header {{
      background: linear-gradient(135deg, #ba9eff, #8455ef);
      width: 100%;
      padding: 1.5rem 2rem;
      text-align: center;
      font-size: 1.8rem;
      font-weight: 700;
      color: #fff;
      letter-spacing: -0.02em;
    }}
    .hero {{
      max-width: 800px;
      text-align: center;
      padding: 4rem 2rem;
    }}
    .hero h1 {{ font-size: 2.5rem; margin-bottom: 1rem; color: #fff; }}
    .hero p {{ font-size: 1.1rem; color: #adaaaa; line-height: 1.7; }}
    .cta {{
      display: inline-block;
      margin-top: 2rem;
      padding: 0.9rem 2.5rem;
      background: linear-gradient(135deg, #ba9eff, #8455ef);
      color: #fff;
      border-radius: 0.75rem;
      font-weight: 600;
      text-decoration: none;
      transition: opacity 0.2s;
    }}
    .cta:hover {{ opacity: 0.85; }}
    footer {{ margin-top: auto; padding: 1.5rem; color: #494847; font-size: 0.8rem; }}
  </style>
</head>
<body>
  <header>🌐 Almatti AI — Generated Website</header>
  <div class="hero">
    <h1>{title}</h1>
    <p>This page was auto-generated by the <strong>Almatti AI Web Builder Agent</strong>.<br/>
    Task: <em>"{task[:200]}"</em></p>
    <a class="cta" href="#">Get Started</a>
  </div>
  <footer>Generated by Almatti AI Workforce &mdash; {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC</footer>
</body>
</html>"""
